-- Categoria: Aceites y Vinagres (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('AOVE Picual Premium', 18.50, 'Aceite de Oliva Virgen Extra de extraccion en frio, variedad Picual. Aroma frutado intenso con ligeras notas picantes, ideal para degustar en crudo.', true, 'Aceites y Vinagres', '2028-12-31', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/543813_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('AOVE Arbequina Temprana', 19.90, 'Elaborado con las primeras aceitunas de la cosecha. Su perfil dulce y almendrado lo convierte en la eleccion perfecta para reposteria fina.', true, 'Aceites y Vinagres', '2028-11-30', 0.15, 'https://static.carrefour.es/hd_510x_/img_pim_food/178237_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('AOVE con Trufa Blanca', 24.50, 'Exquisito aceite de oliva virgen extra infusionado de manera natural con autentica trufa blanca de Alba, aporta un aroma inconfundible a tus pastas.', true, 'Aceites y Vinagres', '2027-10-15', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/962539_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('AOVE Ahumado al Roble', 22.00, 'Innovador aceite de oliva ahumado lentamente con maderas de roble ecologico, aporta un toque de brasa spectacular a carnes y pescados.', true, 'Aceites y Vinagres', '2028-05-20', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/027885_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Vinagre Balsamico 12 anos', 45.00, 'Autentico Aceto Balsamico Tradizionale di Modena envejecido durante 12 anos en barricas de madera noble, densidad extraordinaria y notas a caramelo.', true, 'Aceites y Vinagres', '2036-01-01', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/578567_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Vinagre de Jerez Reserva', 12.50, 'Vinagre D.O. Jerez envejecido bajo el sistema de soleras y criaderas, de color caoba oscuro y un bouquet excepcionalmente punzante y complejo.', true, 'Aceites y Vinagres', '2035-12-31', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/232313_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Vinagre de Manzana Organico', 8.50, 'Vinagre de sidra de manzana ecologico sin pasteurizar y sin filtrar, conserva "la madre" garantizando todas sus propiedades probioticas intactas.', true, 'Aceites y Vinagres', '2029-06-15', 0.10, 'https://static.carrefour.es/hd_510x_/img_pim_food/431762_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Aceite de Sesamo Tostado', 11.20, 'Aceite de semillas de sesamo suavemente tostadas, un pilar de la alta cocina asiatica que aporta un profundo aroma a frutos secos a cualquier wok.', false, 'Aceites y Vinagres', '2027-08-20', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/122427_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Aceite de Aguacate Premium', 14.90, 'Aceite extraido de la pulpa de aguacates Hass madurados al sol, de color esmeralda y textura sedosa, ideal para alinar tartares y ensaladas.', true, 'Aceites y Vinagres', '2028-02-15', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/654756_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Glaseado de Pedro Ximenez', 9.50, 'Reduccion artesanal de vino dulce Pedro Ximenez de pasas, textura de sirope espesa perfecta para decorar platos de quesos curados o foie gras.', true, 'Aceites y Vinagres', '2030-05-10', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/727397_00_1.jpg');

-- Categoria: Conservas del Mar (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Anchoas del Cantabrico "00"', 24.90, 'Lomos de anchoa tamano "00" del mar Cantabrico, sobadas a mano una a una y maduradas en salazon durante 12 meses. Textura carnosa y sin espinas.', true, 'Conservas Gourmet', '2027-04-15', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/854255_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Ventresca de Bonito del Norte', 18.50, 'La parte mas jugosa y delicada del Bonito del Norte pescado a cana, empacada a mano en laminas enteras cubiertas de suave aceite de oliva virgen.', true, 'Conservas Gourmet', '2029-08-30', 0.20, 'https://static.carrefour.es/hd_510x_/img_pim_food/226662_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Mejillones en Escabeche Rias Baixas', 9.90, 'Seleccion de 6/8 mejillones gigantes de batea criados en las Rias Gallegas, fritos en aceite de oliva y banados en un escabeche tradicional casero.', true, 'Conservas Gourmet', '2028-11-20', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/027734_00_2.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Caviar Beluga Imperial 50g', 180.00, 'El mas exclusivo de los caviares, de huevas grandes y textura mantecosa. Un sabor marino suave y persistente que se deshace delicadamente en el paladar.', true, 'Conservas Gourmet', '2026-12-15', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/154240_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Berberechos al Natural 25/35', 22.00, 'Berberechos de las Rias Gallegas de calibre extragrande, depurados cuidadosamente para eliminar toda la arena y conservados unicamente en agua y sal.', false, 'Conservas Gourmet', '2028-09-10', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/511349_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Navajas de las Rias Gallegas', 16.50, 'Navajas extraidas mediante buceo de forma sostenible, empacadas al natural. Carne blanca, firme y con un inigualable sabor a yodo y mar profundo.', true, 'Conservas Gourmet', '2029-03-25', 0.15, 'https://static.carrefour.es/hd_510x_/img_pim_food/124940_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Zamburiñas en Salsa de Vieira', 11.20, 'Pequenas y delicadas zamburinas guisadas lentamente a fuego suave en una salsa casera de tomate, cebolla pochada, aceite de oliva y un toque de vino.', true, 'Conservas Gourmet', '2029-07-15', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/115727_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Sardinillas Millesimees', 14.80, 'Sardinillas francesas de anada, maduradas en lata durante anos. Con el tiempo, la espina se disuelve y la carne se confita en aceite ganando melosidad.', true, 'Conservas Gourmet', '2032-12-31', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/065658_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Pulpo a la Gallega en Conserva', 13.50, 'Trozos selectos de tentaculo de pulpo cocidos en su punto exacto de ternura, alinados con autentico Pimenton de la Vera dulce y aceite de oliva.', true, 'Conservas Gourmet', '2028-06-30', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/335249_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Lomo de Salmon Ahumado Salvaje', 32.00, 'Corazon de lomo de salmon salvaje de Alaska, curado en seco con sal marina y ahumado en frio con maderas nobles. Corte grueso para apreciar su textura.', true, 'Gourmet Frio', '2026-07-20', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/295106_00_1.jpg');

-- Categoria: Conservas Vegetales (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Esparragos Blancos D.O. Navarra', 21.00, 'Esparragos blancos gruesos (calibre 4/6) pelados a mano de la D.O. Navarra. No tienen fibrosidad, son mantecosos y presentan un ligero toque amargo final.', true, 'Conservas Gourmet', '2029-04-15', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/469031_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Pimientos del Piquillo Confitados', 12.50, 'Pimientos del Piquillo de Lodosa asados al sarmiento, pelados sin agua y confitados lentamente en aceite virgen extra. Dulzor caramelizado excepcional.', true, 'Conservas Gourmet', '2028-10-20', 0.10, 'https://static.carrefour.es/hd_510x_/img_pim_food/226678_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Alcachofas Confitadas en AOVE', 16.90, 'Corazones de alcachofa de la variedad Blanca de Tudela, tiernos y sin pelusas interiores, confitados a baja temperatura para preservar toda su jugosidad.', true, 'Conservas Gourmet', '2028-05-15', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/030084_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Tomate Seco de Puglia en Aceite', 9.80, 'Mitades de tomate San Marzano desecados lentamente bajo el sol de Italia, marinados con hierbas provenzales, alcaparras y aceite de oliva.', true, 'Conservas Gourmet', '2027-11-30', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/171490_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Setas Boletus Edulis en Aceite', 18.50, 'Trozos grandes de Boletus Edulis silvestre de temporada, confitados en aceite para utilizarlos al instante en risottos, revueltos o pastas frescas.', true, 'Conservas Gourmet', '2028-12-10', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/502993_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Trufa Negra Entera (Melanosporum)', 35.00, 'Un ejemplar de autentica Trufa Negra de invierno conservada en su propio jugo. El remate mas lujoso para rallar directamente sobre huevos o pures.', true, 'Gourmet Exclusivo', '2027-02-28', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/401341_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Aceitunas Gordal Rellenas', 6.50, 'Aceitunas de mesa calibre Gordal, de carne muy firme, deshuesadas y rellenas manualmente con tiras de pimiento asado y almendra marcona tostada.', true, 'Aperitivos', '2028-08-15', 0.25, 'https://static.carrefour.es/hd_510x_/img_pim_food/722332_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Alcaparrones de Andalucia', 5.90, 'El fruto de la alcaparra recolectado con su pedunculo, encurtido en vinagre suave. Su crujido y acidez limpian el paladar y abren el apetito.', true, 'Aperitivos', '2029-01-20', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/164831_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Mermelada de Cebolla Caramelizada', 7.50, 'Cebolla dulce pochada durante horas hasta alcanzar la caramelizacion natural de sus propios azucares. Sublime combinacion con queso de cabra y foie.', true, 'Conservas Gourmet', '2028-03-12', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/706014_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Corazones de Palmito Enteros', 8.90, 'Palmitos silvestres traidos de la selva tropical, muy crujientes y refrescantes. Su delicado sabor a nuez los hace destacar en ensaladas premium.', true, 'Conservas Gourmet', '2027-09-30', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/015497_00_1.jpg');

-- Categoria: Quesos Artesanos (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Queso Manchego Anejo D.O.', 28.50, 'Queso elaborado con leche cruda de oveja manchega y madurado mas de 12 meses. Textura escamosa, sabor potente, picante y muy persistente en boca.', true, 'Quesos', '2027-02-15', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/678754_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Pecorino Romano con Trufa', 32.00, 'Tradicional queso de oveja italiano infiltrado durante su maduracion con vetas de trufa negra de verano, una explosion de sabor umami inigualable.', true, 'Quesos', '2026-12-10', 0.15, 'https://static.carrefour.es/hd_510x_/img_pim_food/678073_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Queso Roquefort AOC Selection', 24.00, 'Considerado el rey de los quesos azules franceses, elaborado con leche de oveja y madurado en las cuevas naturales de Roquefort-sur-Soulzon.', true, 'Quesos', '2026-09-20', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/684524_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Brie de Meaux Leche Cruda', 21.50, 'Queso de pasta blanda y corteza enmohecida blanca, fabricado artesanalmente con leche cruda de vaca. Su interior fluido sabe a mantequilla y champinon.', false, 'Quesos', '2026-07-05', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/684441_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Parmigiano Reggiano 36 Meses', 36.00, 'El autentico parmesano de montana con una maduracion de tres anos. Presenta cristales de tirosina que crujen, ideal para comer en lascas o rallado.', true, 'Quesos', '2028-05-30', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/670304_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Queso Comte AOC 24 Meses', 34.50, 'Queso de pasta prensada cocida de los Alpes franceses, su larga maduracion le confiere notas tostadas, a nueces, caramelo y aromas de frutas maduras de otono.', true, 'Quesos', '2027-04-10', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/712252_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Queso Azul de Valdeon I.G.P.', 19.80, 'Queso azul leones envuelto tradicionalmente en hojas de platano. Fuerte, mantecoso y muy untuoso, de sabor intenso perfecto para salas de carne.', true, 'Quesos', '2026-11-15', 0.10, 'https://static.carrefour.es/hd_510x_/img_pim_food/130653_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Torta del Casar D.O.P.', 26.00, 'Queso extremeno de oveja cuajado con cardo silvestre. Su corteza rustica esconde un interior totalmente liquido con un retrogusto ligeramente amargo.', true, 'Quesos', '2026-08-30', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/687191_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Queso Gouda Extra Curado Oude', 22.50, 'Gouda holandes envejecido mas de 18 meses, de color anaranjado oscuro y textura quebradiza. Sabor denso, salino y con recuerdos claros a toffee dulce.', true, 'Quesos', '2027-08-20', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/681576_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Queso Stilton Vintage', 30.00, 'Queso azul ingles clasico, de textura untuosa a pesar de su firmeza. Menos salado que el Roquefort, marida a la perfeccion con vinos de Oporto.', true, 'Quesos', '2026-10-10', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/685513_00_1.jpg');

-- Categoria: Embutidos Ibericos y Foie (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Jamon Iberico 100% Bellota D.O.', 85.00, 'Sobres de jamon cortado a cuchillo por maestros jamoneros. Cerdos de raza iberica pura criados en libertad y alimentados exclusivamente de bellotas.', true, 'Charcuteria Selecta', '2026-12-31', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/175132_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Paleta Iberica Bellota Deshuesada', 65.00, 'Centro de paleta iberica de bellota lista para cortar a maquina en casa. Alta infiltracion de grasa que se deshace y funde a temperatura ambiente.', true, 'Charcuteria Selecta', '2027-03-15', 0.20, 'https://static.carrefour.es/hd_510x_/img_pim_food/594870_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Lomo Iberico de Bellota Media Pieza', 45.00, 'Cana de lomo adobada artesanalmente con Pimenton de la Vera y curada en secaderos naturales. Su bajo contenido en grasa externa realza su sabor.', true, 'Charcuteria Selecta', '2027-01-20', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/730430_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Salchichon Iberico Cular con Trufa', 24.50, 'Embutido en tripa cular natural, elaborado con carnes nobles de cerdo iberico picadas finamente y aromatizadas con ralladura de trufa negra.', true, 'Charcuteria Selecta', '2026-11-30', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/402119_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Chorizo Iberico de Bellota Cular', 22.00, 'Elaborado con el mejor magro de cerdo iberico y el toque inconfundible de ajo morado y pimenton extremeno, logrando un equilibrio aromatico perfecto.', true, 'Charcuteria Selecta', '2026-11-30', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/709428_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Cecina de Leon I.G.P. Reserva', 32.00, 'Pierna de vacuno mayor curada y ligeramente ahumada en madera de encina, madurada durante mas de 12 meses. Una alternativa sabrosa y sin apenas grasa.', true, 'Charcuteria Selecta', '2027-05-15', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/313083_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Foie Gras Entier de Pato (Tarro)', 48.00, 'Lobulo entero de higado de pato cebado meticulosamente desvenado a mano, semicocido en su propia grasa y sazonado sutilmente con sal, pimienta y Armanac.', true, 'Gourmet Frio', '2028-02-28', 0.10, 'https://static.carrefour.es/hd_510x_/img_pim_food/575825_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Bloc de Foie Gras con Trufa Negra', 35.00, 'Emulsion fina y homogenea de higado graso de pato, enriquecida con generosos trozos de trufa de invierno (3%). Ideal para untar en tostas calientes.', true, 'Gourmet Frio', '2029-06-30', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/710414_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Sobrasada de Cerdo Negro Mallorquin', 26.50, 'Autentica sobrasada artesanal de raza porcina autoctona de Mallorca, curada en tripa natural. Un manjar iberico para untar de textura fundente y sedosa.', false, 'Charcuteria Selecta', '2026-10-15', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/709523_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Coppa Italiana Curada', 28.00, 'Cabecero de lomo de cerdo al estilo italiano tradicional, marinado en vino tinto, frotado con especias y curado al aire, de vetado espectacular.', true, 'Charcuteria Selecta', '2026-09-30', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/479157_00_1.jpg');

-- Categoria: Dulces, Mermeladas y Mieles (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Mermelada Extra de Higo y Nuez', 8.50, 'Elaborada artesanalmente con higos negros de temporada y nueces tostadas troceadas, un acompanamiento indispensable para cualquier tabla de quesos fuertes.', true, 'Dulces', '2028-05-10', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/335913_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Mermelada de Naranja Amarga Sevilla', 7.90, 'Autentica receta britanica elaborada con naranjas amargas recogidas en los patios sevillanos, la proporcion perfecta de dulzor citrico y cascara.', true, 'Dulces', '2028-08-20', 0.15, 'https://static.carrefour.es/hd_510x_/img_pim_food/163977_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Crema de Gianduja Artesana', 15.50, 'Exquisita crema de avellanas del Piamonte (45%) trituradas a la piedra con chocolate con leche puro, sin aceites de palma anadidos ni grasas artificiales.', true, 'Dulces', '2027-11-30', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/399348_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Miel Cruda de Romero', 12.00, 'Miel pura y sin pasteurizar extraida en frio de los montes mediterraneos. Color muy claro, aroma balsamico y propiedades beneficiosas para la garganta.', true, 'Dulces', '2030-12-31', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/509625_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Miel de Acacia con Trufa Blanca', 18.50, 'Miel italiana muy suave de Acacia, en la cual macera finas laminas de trufa blanca de Alba. El contraste dulce-terroso es magico sobre quesos azules.', true, 'Dulces', '2029-12-31', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/635706_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Marron Glace Seleccion Especial', 28.00, 'Castanas confitadas enteras de gran calibre sumergidas pacientemente en un almibar ligero y vainillado, el pinaculo de la reposteria artesana otonal.', true, 'Dulces', '2027-01-30', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/257720_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Turron de Jijona Artesano I.G.P.', 16.50, 'Turron blando maestro elaborado en molino de piedra tradicional, usando miel de romero y mas de un 70% de almendra marcona cruda finamente molida.', true, 'Dulces', '2027-04-15', 0.10, 'https://static.carrefour.es/hd_510x_/img_pim_food/575931_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Caja de Bombones Belgas Praline', 35.00, 'Surtido premium de 24 bombones elaborados a mano por maestros chocolateros belgas. Rellenos de ganache, praline de avellanas, caramelo y mazapan.', true, 'Dulces', '2026-10-30', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/001994_00_2.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Tableta Chocolate Cacao 100% Criollo', 9.50, 'Tableta rustica de cacao criollo extremo de origen unico sin azucares anadidos, su intensa acidez frutal y largo postgusto desafian el paladar.', true, 'Dulces', '2028-02-15', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/189683_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Crema de Pistacho de Bronte D.O.P.', 22.00, 'Intensa pasta dulce para untar elaborada exclusivamente con pistachos verdes procedentes del suelo volcanico siciliano de Bronte, una rareza gourmet.', false, 'Dulces', '2027-06-20', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/672382_00_1.jpg');

-- Categoria: Vinos y Licores (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Vino Tinto Rioja Gran Reserva', 45.00, 'Un tinto elegante de la D.O.Ca. Rioja madurado 36 meses en roble americano y afinado en botella, desvela sedosas notas a vainilla, cuero y fruta compotada.', true, 'Vinos y Licores', '2040-12-31', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/238226_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Vino Tinto Ribera del Duero Crianza', 26.50, 'Elaborado con Tempranillo 100%, con 12 meses en barrica nueva de roble frances. Destaca su estructura, tanino potente y aromas de fruta negra.', true, 'Vinos y Licores', '2035-12-31', 0.20, 'https://static.carrefour.es/hd_510x_/img_pim_food/013290_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Vino Blanco Albarino Rias Baixas', 19.80, 'Blanco atlantico joven, brillante y salino, con penetrante aroma floral a jazmin y frutas de hueso. La pareja innegable para todo tipo de marisco.', true, 'Vinos y Licores', '2030-12-31', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/242614_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Vino Blanco Borgona Chablis Premier Cru', 55.00, 'Vino blanco de la uva Chardonnay fermentado en acero, caracterizado por su pureza mineral, frescura acida de piedra de tiza y sutil final citrico.', true, 'Vinos y Licores', '2034-12-31', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/779794_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Champagne Millesime Brut', 75.00, 'Champagne frances de anada, elaborado a partir de vinedos Grand Cru. Presenta burbuja diminuta y elegantes toques aromaticos a brioche y bolleria tostada.', true, 'Vinos y Licores', '2040-12-31', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/103357_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Cava Gran Reserva Brut Nature', 24.00, 'Cava sin azucares anadidos tras su deguelle, reposado mas de 30 meses en rima. Extraordinariamente seco, crujiente, estructurado y de gran integracion carbonica.', true, 'Vinos y Licores', '2032-12-31', 0.15, 'https://static.carrefour.es/hd_510x_/img_pim_food/033924_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Vermut Rojo Artesano de Barrica', 16.50, 'Maceracion de 40 botanicos diferentes sobre un vino blanco de calidad, envejecido en botas centenarias para conseguir amargor y toques amaderados especiados.', true, 'Vinos y Licores', '2038-12-31', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/896537_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Ginebra Premium Botanica London Dry', 38.00, 'Destilada lentamente en alambiques de cobre usando enebro silvestre, cardamomo, cilantro y citricos frescos mediterraneos. Muy limpia y refrescante.', true, 'Vinos y Licores', '2050-12-31', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/017446_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Ron Agricola Anejo Solera 15 Años', 65.00, 'Elaborado con jugo de cana puro en lugar de melazas, madurado en barricas ex-bourbon. Muy denso y complejo, rebosante de notas de toffee y cacao.', true, 'Vinos y Licores', '2050-12-31', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/424054_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Vino Dulce Pedro Ximenez V.O.R.S.', 85.00, 'Autentica reliquia de Jerez con mas de 30 anos de crianza certificada. El mosto densificado de pasas soleadas crea un elixir oscuro que sabe a higos.', true, 'Vinos y Licores', '2050-12-31', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/501502_00_1.jpg');

-- Categoria: Salsas y Especias (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Flor de Sal de d''Es Trenc', 12.50, 'Los primeros cristales puros que flotan al amanecer en las salinas de Mallorca, cosechados artesanalmente. Se funden en boca ensalzando carnes a la brasa.', true, 'Especias', '2035-12-31', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/207986_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Sal Rosa del Himalaya Gruesa', 8.90, 'Extraida de antiguas minas de sal en Pakistan, no esta tratada ni refinada y es rica en hierro y minerales esenciales, ideal para el uso en molinillo.', true, 'Especias', '2035-12-31', 0.10, 'https://static.carrefour.es/hd_510x_/img_pim_food/852290_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Azafran de La Mancha D.O.P.', 22.00, 'Tarro de cristal con hebras puras de azafran manchego, secado a fuego lento de lena. Una pizca de este "oro rojo" aporta profundo sabor y color a tus arroces.', true, 'Especias', '2028-11-30', 0.0, 'https://static.carrefour.es/hd_1500x_/img_pim_food/381768_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Pimienta Negra de Kampot I.G.P.', 15.50, 'Considerada por chefs y criticos como la mejor pimienta negra del mundo, con unas sorprendentes notas herbales y de mentol fresco que perduran tras la molienda.', true, 'Especias', '2029-05-15', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/496585_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Mostaza a la Antigua de Dijon', 7.50, 'Receta original en tarro de gres, contiene las semillas de mostaza enteras mezcladas con vino blanco, otorgando un caracter picante, rustico y crujiente.', true, 'Salsas', '2028-04-20', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/002264_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Pesto Genovese Fresco D.O.P.', 11.20, 'Preparado artesanalmente solo con albahaca genovesa de hoja pequena, pinones europeos, ajo dulce y Parmigiano, un viaje rapido al frescor de Italia.', false, 'Salsas', '2026-07-15', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/224281_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Salsa Tartufata (Crema de Trufa)', 16.00, 'Exquisita crema densa elaborada a partir de champinones picados, aceite de oliva virgen extra, especias y un 5% de autentica trufa negra de verano.', true, 'Salsas', '2028-08-10', 0.20, 'https://static.carrefour.es/hd_510x_/img_pim_food/199739_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Pasta de Curry Rojo Tailandes', 6.80, 'Pasta concentrada de especias asiaticas y chiles frescos machacados a mortero, la base fundamental para elaborar currys tailandeses muy aromaticos y picantes.', true, 'Salsas', '2028-10-30', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/799553_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Salsa de Soja Shoyu Artesanal', 14.50, 'Salsa fermentada lentamente en barriles de cedro durante mas de un ano en Japon. De sabor extremadamente complejo y umami profundo sin ser salada en exceso.', true, 'Salsas', '2029-01-15', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/082853_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Pimenton de la Vera Dulce D.O.P.', 5.90, 'Latita metalica de pimenton secado y ahumado al humo de roble y encina en la region de Caceres, confiriendo a los embutidos y guisos un sabor inigualable.', true, 'Especias', '2029-03-10', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/512617_00_1.jpg');

-- Categoria: Pastas y Arroces Gourmet (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Arroz Bomba D.O. Valencia', 7.50, 'El arroz clasico para grandes paellas, su grano redondo no se rompe y tiene una altisima capacidad de absorber todos los matices y el sabor de los caldos.', true, 'Pastas y Arroces', '2028-06-30', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/215410_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Arroz Carnaroli Especial Risotto', 8.20, 'Cosechado en la zona del Piamonte italiano, contiene mucho almidon, que se libera lentamente permitiendo la textura melosa perfecta en todo risotto.', true, 'Pastas y Arroces', '2028-09-15', 0.15, 'https://static.carrefour.es/hd_510x_/img_pim_food/670793_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Pasta Pappardelle al Huevo Artesana', 9.50, 'Largas cintas de pasta gruesa trefiladas en bronce para lograr rugosidad. El huevo campero aporta un color amarillo intenso y gran riqueza de sabor.', true, 'Pastas y Arroces', '2027-10-20', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/982057_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Spaghetti al Nero di Seppia', 8.90, 'Finos espaguetis oscurecidos naturalmente amasados con tinta de sepia, los cuales otorgan un evocador sabor a mar y resultan visualmente sorprendentes en el plato.', true, 'Pastas y Arroces', '2027-11-15', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/336301_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Raviolis Secos Rellenos de Trufa', 12.00, 'Pasta corta muy fina rellena y secada, que al hidratarse recupera un delicioso corazon trufado que inunda de aromas la cocina entera al hervirse.', false, 'Pastas y Arroces', '2027-05-10', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/696250_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Macarrones Gigantes Paccheri', 7.90, 'Pasta napolitana artesanal con forma de enormes tubos de semola de trigo duro. Quedan muy firmes y resisten ragus de carnes espesas e intensas.', true, 'Pastas y Arroces', '2028-01-30', 0.10, 'https://static.carrefour.es/hd_510x_/img_pim_food/655354_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Lentejas Caviar Beluga Organicas', 6.50, 'Llamadas asi por su parecido estetico al caviar, son pequenas, de piel oscura y textura entera tras cocerlas, sin apenas deshacerse en ensaladas frias.', true, 'Legumbres Selectas', '2028-11-15', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/030045_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Garbanzo Blanco Lechoso Andaluz', 7.20, 'Un garbanzo extra grueso y muy mantecoso al paladar que no suelta la piel. Un lujo imprescindible para preparar cocidos a fuego lento y potajes de bacalao.', true, 'Legumbres Selectas', '2028-10-10', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/728772_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Alubia Tolosana (Pinta de Tolosa)', 8.50, 'Grano purpureo casi negro, una vez cocida lentamente se vuelve mantequilla pura desatando un caldo tan espeso y sedoso que sorprende gratamente.', true, 'Legumbres Selectas', '2028-10-10', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/032628_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Quinoa Real Boliviana Organica', 6.90, 'Seudocereal milenario andino de gran tamano cultivado a alta altitud, libre de impurezas y muy rico en proteinas vegetales de asimilacion completa.', true, 'Pastas y Arroces', '2028-04-20', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/685898_00_1.jpg');

-- Categoria: Cafes, Tes e Infusiones (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Cafe Jamaica Blue Mountain', 55.00, 'Considerado uno de los mejores cafes del mundo y cultivado a mas de 2000 metros, tiene acidez suave, nada de amargor y cuerpo floral elegante.', true, 'Cafes y Tes', '2027-12-31', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/643314_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Cafe Colombia Geisha Especialidad', 32.00, 'Granos de la cotizada variedad botanica Geisha, de proceso lavado. Perfil de cata asombrosamente afrutado con potentes notas a melocoton y jazmin.', true, 'Cafes y Tes', '2027-10-15', 0.20, 'https://static.carrefour.es/hd_510x_/img_pim_food/912144_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Cafe Etiopia Yirgacheffe Grano', 18.50, 'Cafe arabica de origen africano procesado al natural, desprende olores a bergamota y te negro, ideal para disfrutar en preparaciones de filtro manual.', true, 'Cafes y Tes', '2027-08-30', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/234798_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Te Matcha Ceremonial Grado A', 45.00, 'Polvo de te verde molido a la piedra proveniente de los mejores cultivos de sombra de Uji en Japon. Su amargor es nulo y su color es verde esmeralda brillante.', true, 'Cafes y Tes', '2027-06-15', 0.0, 'https://storage.googleapis.com/catalog-pictures-carrefour-es/catalog/pictures/hd_510x_/3666879017081_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Te Negro Earl Grey Premium', 14.50, 'Hojas completas de te negro de altura de la region de Assam delicadamente perfumadas con aceite esencial puro extraido de bergamotas de la region de Calabria.', true, 'Cafes y Tes', '2028-05-10', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/032806_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Te Verde Sencha Japones (Hojas)', 16.00, 'Te verde no fermentado y cocido al vapor siguiendo el metodo de Japon tradicional, libera un sabor refrescante, profundamente vegetal y muy iodado.', true, 'Cafes y Tes', '2028-01-20', 0.15, 'https://static.carrefour.es/hd_510x_/img_pim_food/786724_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Te Blanco Agujas de Plata (Silver Needle)', 28.00, 'Te muy raro cosechado a mano usando unicamente los primeros y tiernos brotes blancos vellosos antes de que la hoja se abra al sol de primavera chino.', false, 'Cafes y Tes', '2027-11-30', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/787794_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Infusion Frutos del Bosque Salvajes', 11.00, 'Mezcla de hibisco, rosa mosqueta, bayas de sauco y arandanos, infusion sin nada de teina, muy saludable y afrutada, deliciosa tanto en frio como en caliente.', true, 'Cafes y Tes', '2028-09-15', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/814373_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Cafe Descafeinado Swiss Water', 19.00, 'Granos de arabica organicos libres de cafeina al 99.9% gracias al costoso proceso ecologico con agua natural que conserva perfectamente su rico perfil aromatico.', true, 'Cafes y Tes', '2027-10-10', 0.0, 'https://static.carrefour.es/hd_510x_/img_pim_food/081050_00_1.jpg');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Te Oolong Tie Guan Yin Premium', 26.00, 'Oolong semifermentado de la provincia china de Fujian, famoso por su aroma floral intenso y su sabor mantecoso con matices a orquídea. Ideal para múltiples infusiones sin perder complejidad.', true, 'Cafes y Tes', '2028-03-12', 0.0, 'https://storage.googleapis.com/catalog-pictures-carrefour-es/catalog/pictures/hd_510x_/4024075500506_1.jpg');


INSERT INTO usuario (dtype, codigo_usuario, username, password, roles, nombre, apellidos, email, telefono) VALUES ('A', 1001, 'admin', '{noop}admin', 'ADMIN', 'Administrador', 'Sistema', 'admin@tienda.com', '600000000');
INSERT INTO usuario (dtype, codigo_usuario, username, password, roles, nombre, apellidos, email, telefono) VALUES ('C', 1002, 'user', '{noop}user', 'CLIENTE', 'Usuario', 'Normal', 'user@tienda.com', '600000001');

-- Pedidos de ejemplo (sin cliente asociado)
INSERT INTO pedido (fecha, total) VALUES ('2026-05-01 10:30:00', 127.42);
INSERT INTO pedido (fecha, total) VALUES ('2026-05-05 14:15:00', 124.50);
INSERT INTO pedido (fecha, total) VALUES ('2026-05-10 09:00:00', 46.39);
INSERT INTO pedido (fecha, total) VALUES ('2026-05-15 17:45:00', 127.42);
INSERT INTO pedido (fecha, total) VALUES ('2026-05-22 11:20:00', 137.00);

-- Lineas del Pedido 1
INSERT INTO linea_pedido (cantidad, codigo_pedido, producto_id) VALUES (2, 1, 1);
INSERT INTO linea_pedido (cantidad, codigo_pedido, producto_id) VALUES (1, 1, 2);
INSERT INTO linea_pedido (cantidad, codigo_pedido, producto_id) VALUES (3, 1, 3);

-- Lineas del Pedido 2
INSERT INTO linea_pedido (cantidad, codigo_pedido, producto_id) VALUES (1, 2, 4);
INSERT INTO linea_pedido (cantidad, codigo_pedido, producto_id) VALUES (2, 2, 5);
INSERT INTO linea_pedido (cantidad, codigo_pedido, producto_id) VALUES (1, 2, 6);

-- Lineas del Pedido 3
INSERT INTO linea_pedido (cantidad, codigo_pedido, producto_id) VALUES (2, 3, 7);
INSERT INTO linea_pedido (cantidad, codigo_pedido, producto_id) VALUES (1, 3, 8);
INSERT INTO linea_pedido (cantidad, codigo_pedido, producto_id) VALUES (1, 3, 9);

-- Lineas del Pedido 4
INSERT INTO linea_pedido (cantidad, codigo_pedido, producto_id) VALUES (2, 4, 1);
INSERT INTO linea_pedido (cantidad, codigo_pedido, producto_id) VALUES (1, 4, 2);
INSERT INTO linea_pedido (cantidad, codigo_pedido, producto_id) VALUES (3, 4, 3);

-- Lineas del Pedido 5
INSERT INTO linea_pedido (cantidad, codigo_pedido, producto_id) VALUES (1, 5, 4);
INSERT INTO linea_pedido (cantidad, codigo_pedido, producto_id) VALUES (2, 5, 5);
INSERT INTO linea_pedido (cantidad, codigo_pedido, producto_id) VALUES (2, 5, 6);

ALTER TABLE pedido ALTER COLUMN codigo_pedido RESTART WITH 6;
ALTER TABLE producto ALTER COLUMN codigo_producto RESTART WITH 120;
ALTER TABLE linea_pedido ALTER COLUMN id RESTART WITH 16;
