-- Categoría: Aceites y Vinagres (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('AOVE Picual Premium', 18.50, 'Aceite de Oliva Virgen Extra de extracción en frío, variedad Picual. Aroma frutado intenso con ligeras notas picantes, ideal para degustar en crudo.', true, 'Aceites y Vinagres', '2028-12-31', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('AOVE Arbequina Temprana', 19.90, 'Elaborado con las primeras aceitunas de la cosecha. Su perfil dulce y almendrado lo convierte en la elección perfecta para repostería fina.', true, 'Aceites y Vinagres', '2028-11-30', 0.15, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('AOVE con Trufa Blanca', 24.50, 'Exquisito aceite de oliva virgen extra infusionado de manera natural con auténtica trufa blanca de Alba, aporta un aroma inconfundible a tus pastas.', true, 'Aceites y Vinagres', '2027-10-15', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('AOVE Ahumado al Roble', 22.00, 'Innovador aceite de oliva ahumado lentamente con maderas de roble ecológico, aporta un toque de brasa espectacular a carnes y pescados.', true, 'Aceites y Vinagres', '2028-05-20', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Vinagre Balsámico 12 años', 45.00, 'Auténtico Aceto Balsamico Tradizionale di Modena envejecido durante 12 años en barricas de madera noble, densidad extraordinaria y notas a caramelo.', true, 'Aceites y Vinagres', '2036-01-01', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Vinagre de Jerez Reserva', 12.50, 'Vinagre D.O. Jerez envejecido bajo el sistema de soleras y criaderas, de color caoba oscuro y un bouquet excepcionalmente punzante y complejo.', true, 'Aceites y Vinagres', '2035-12-31', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Vinagre de Manzana Orgánico', 8.50, 'Vinagre de sidra de manzana ecológico sin pasteurizar y sin filtrar, conserva "la madre" garantizando todas sus propiedades probióticas intactas.', true, 'Aceites y Vinagres', '2029-06-15', 0.10, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Aceite de Sésamo Tostado', 11.20, 'Aceite de semillas de sésamo suavemente tostadas, un pilar de la alta cocina asiática que aporta un profundo aroma a frutos secos a cualquier wok.', false, 'Aceites y Vinagres', '2027-08-20', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Aceite de Aguacate Premium', 14.90, 'Aceite extraído de la pulpa de aguacates Hass madurados al sol, de color esmeralda y textura sedosa, ideal para aliñar tartares y ensaladas.', true, 'Aceites y Vinagres', '2028-02-15', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Glaseado de Pedro Ximénez', 9.50, 'Reducción artesanal de vino dulce Pedro Ximénez de pasas, textura de sirope espesa perfecta para decorar platos de quesos curados o foie gras.', true, 'Aceites y Vinagres', '2030-05-10', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');

-- Categoría: Conservas del Mar (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Anchoas del Cantábrico "00"', 24.90, 'Lomos de anchoa tamaño "00" del mar Cantábrico, sobadas a mano una a una y maduradas en salazón durante 12 meses. Textura carnosa y sin espinas.', true, 'Conservas Gourmet', '2027-04-15', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Ventresca de Bonito del Norte', 18.50, 'La parte más jugosa y delicada del Bonito del Norte pescado a caña, empacada a mano en láminas enteras cubiertas de suave aceite de oliva virgen.', true, 'Conservas Gourmet', '2029-08-30', 0.20, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Mejillones en Escabeche Rías Baixas', 9.90, 'Selección de 6/8 mejillones gigantes de batea criados en las Rías Gallegas, fritos en aceite de oliva y bañados en un escabeche tradicional casero.', true, 'Conservas Gourmet', '2028-11-20', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Caviar Beluga Imperial 50g', 180.00, 'El más exclusivo de los caviares, de huevas grandes y textura mantecosa. Un sabor marino suave y persistente que se deshace delicadamente en el paladar.', true, 'Conservas Gourmet', '2026-12-15', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Berberechos al Natural 25/35', 22.00, 'Berberechos de las Rías Gallegas de calibre extragrande, depurados cuidadosamente para eliminar toda la arena y conservados únicamente en agua y sal.', false, 'Conservas Gourmet', '2028-09-10', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Navajas de las Rías Gallegas', 16.50, 'Navajas extraídas mediante buceo de forma sostenible, empacadas al natural. Carne blanca, firme y con un inigualable sabor a yodo y mar profundo.', true, 'Conservas Gourmet', '2029-03-25', 0.15, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Zamburiñas en Salsa de Vieira', 11.20, 'Pequeñas y delicadas zamburiñas guisadas lentamente a fuego suave en una salsa casera de tomate, cebolla pochada, aceite de oliva y un toque de vino.', true, 'Conservas Gourmet', '2029-07-15', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Sardinillas Millésimées', 14.80, 'Sardinillas francesas de añada, maduradas en lata durante años. Con el tiempo, la espina se disuelve y la carne se confita en aceite ganando melosidad.', true, 'Conservas Gourmet', '2032-12-31', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Pulpo a la Gallega en Conserva', 13.50, 'Trozos selectos de tentáculo de pulpo cocidos en su punto exacto de ternura, aliñados con auténtico Pimentón de la Vera dulce y aceite de oliva.', true, 'Conservas Gourmet', '2028-06-30', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Lomo de Salmón Ahumado Salvaje', 32.00, 'Corazón de lomo de salmón salvaje de Alaska, curado en seco con sal marina y ahumado en frío con maderas nobles. Corte grueso para apreciar su textura.', true, 'Gourmet Frío', '2026-07-20', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');

-- Categoría: Conservas Vegetales (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Espárragos Blancos D.O. Navarra', 21.00, 'Espárragos blancos gruesos (calibre 4/6) pelados a mano de la D.O. Navarra. No tienen fibrosidad, son mantecosos y presentan un ligero toque amargo final.', true, 'Conservas Gourmet', '2029-04-15', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Pimientos del Piquillo Confitados', 12.50, 'Pimientos del Piquillo de Lodosa asados al sarmiento, pelados sin agua y confitados lentamente en aceite virgen extra. Dulzor caramelizado excepcional.', true, 'Conservas Gourmet', '2028-10-20', 0.10, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Alcachofas Confitadas en AOVE', 16.90, 'Corazones de alcachofa de la variedad Blanca de Tudela, tiernos y sin pelusas interiores, confitados a baja temperatura para preservar toda su jugosidad.', true, 'Conservas Gourmet', '2028-05-15', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Tomate Seco de Puglia en Aceite', 9.80, 'Mitades de tomate San Marzano desecados lentamente bajo el sol de Italia, marinados con hierbas provenzales, alcaparras y aceite de oliva.', true, 'Conservas Gourmet', '2027-11-30', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Setas Boletus Edulis en Aceite', 18.50, 'Trozos grandes de Boletus Edulis silvestre de temporada, confitados en aceite para utilizarlos al instante en risottos, revueltos o pastas frescas.', true, 'Conservas Gourmet', '2028-12-10', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Trufa Negra Entera (Melanosporum)', 35.00, 'Un ejemplar de auténtica Trufa Negra de invierno conservada en su propio jugo. El remate más lujoso para rallar directamente sobre huevos o purés.', true, 'Gourmet Exclusivo', '2027-02-28', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Aceitunas Gordal Rellenas', 6.50, 'Aceitunas de mesa calibre Gordal, de carne muy firme, deshuesadas y rellenas manualmente con tiras de pimiento asado y almendra marcona tostada.', true, 'Aperitivos', '2028-08-15', 0.25, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Alcaparrones de Andalucía', 5.90, 'El fruto de la alcaparra recolectado con su pedúnculo, encurtido en vinagre suave. Su crujido y acidez limpian el paladar y abren el apetito.', true, 'Aperitivos', '2029-01-20', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Mermelada de Cebolla Caramelizada', 7.50, 'Cebolla dulce pochada durante horas hasta alcanzar la caramelización natural de sus propios azúcares. Sublime combinación con queso de cabra y foie.', true, 'Conservas Gourmet', '2028-03-12', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Corazones de Palmito Enteros', 8.90, 'Palmitos silvestres traídos de la selva tropical, muy crujientes y refrescantes. Su delicado sabor a nuez los hace destacar en ensaladas premium.', true, 'Conservas Gourmet', '2027-09-30', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');

-- Categoría: Quesos Artesanos (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Queso Manchego Añejo D.O.', 28.50, 'Queso elaborado con leche cruda de oveja manchega y madurado más de 12 meses. Textura escamosa, sabor potente, picante y muy persistente en boca.', true, 'Quesos', '2027-02-15', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Pecorino Romano con Trufa', 32.00, 'Tradicional queso de oveja italiano infiltrado durante su maduración con vetas de trufa negra de verano, una explosión de sabor umami inigualable.', true, 'Quesos', '2026-12-10', 0.15, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Queso Roquefort AOC Sélection', 24.00, 'Considerado el rey de los quesos azules franceses, elaborado con leche de oveja y madurado en las cuevas naturales de Roquefort-sur-Soulzon.', true, 'Quesos', '2026-09-20', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Brie de Meaux Leche Cruda', 21.50, 'Queso de pasta blanda y corteza enmohecida blanca, fabricado artesanalmente con leche cruda de vaca. Su interior fluido sabe a mantequilla y champiñón.', false, 'Quesos', '2026-07-05', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Parmigiano Reggiano 36 Meses', 36.00, 'El auténtico parmesano de montaña con una maduración de tres años. Presenta cristales de tirosina que crujen, ideal para comer en lascas o rallado.', true, 'Quesos', '2028-05-30', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Queso Comté AOC 24 Meses', 34.50, 'Queso de pasta prensada cocida de los Alpes franceses, su larga maduración le confiere notas tostadas, a nueces, caramelo y frutas maduras de otoño.', true, 'Quesos', '2027-04-10', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Queso Azul de Valdeón I.G.P.', 19.80, 'Queso azul leonés envuelto tradicionalmente en hojas de plátano. Fuerte, mantecoso y muy untuoso, de sabor intenso perfecto para salsas de carne.', true, 'Quesos', '2026-11-15', 0.10, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Torta del Casar D.O.P.', 26.00, 'Queso extremeño de oveja cuajado con cardo silvestre. Su corteza rústica esconde un interior totalmente líquido con un retrogusto ligeramente amargo.', true, 'Quesos', '2026-08-30', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Queso Gouda Extra Curado Oude', 22.50, 'Gouda holandés envejecido más de 18 meses, de color anaranjado oscuro y textura quebradiza. Sabor denso, salino y con recuerdos claros a toffe dulce.', true, 'Quesos', '2027-08-20', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Queso Stilton Vintage', 30.00, 'Queso azul inglés clásico, de textura untuosa a pesar de su firmeza. Menos salado que el Roquefort, marida a la perfección con vinos de Oporto.', true, 'Quesos', '2026-10-10', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');

-- Categoría: Embutidos Ibéricos y Foie (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Jamón Ibérico 100% Bellota D.O.', 85.00, 'Sobres de jamón cortado a cuchillo por maestros jamoneros. Cerdos de raza ibérica pura criados en libertad y alimentados exclusivamente de bellotas.', true, 'Charcutería Selecta', '2026-12-31', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Paleta Ibérica Bellota Deshuesada', 65.00, 'Centro de paleta ibérica de bellota lista para cortar a máquina en casa. Alta infiltración de grasa que se deshace y funde a temperatura ambiente.', true, 'Charcutería Selecta', '2027-03-15', 0.20, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Lomo Ibérico de Bellota Media Pieza', 45.00, 'Caña de lomo adobada artesanalmente con Pimentón de la Vera y curada en secaderos naturales. Su bajo contenido en grasa externa realza su sabor.', true, 'Charcutería Selecta', '2027-01-20', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Salchichón Ibérico Cular con Trufa', 24.50, 'Embutido en tripa cular natural, elaborado con carnes nobles de cerdo ibérico picadas finamente y aromatizadas con ralladura de trufa negra.', true, 'Charcutería Selecta', '2026-11-30', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Chorizo Ibérico de Bellota Cular', 22.00, 'Elaborado con el mejor magro de cerdo ibérico y el toque inconfundible de ajo morado y pimentón extremeño, logrando un equilibrio aromático perfecto.', true, 'Charcutería Selecta', '2026-11-30', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Cecina de León I.G.P. Reserva', 32.00, 'Pierna de vacuno mayor curada y ligeramente ahumada en madera de encina, madurada durante más de 12 meses. Una alternativa sabrosa y sin apenas grasa.', true, 'Charcutería Selecta', '2027-05-15', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Foie Gras Entier de Pato (Tarro)', 48.00, 'Lóbulo entero de hígado de pato cebado meticulosamente desvenado a mano, semicocido en su propia grasa y sazonado sutilmente con sal, pimienta y Armañac.', true, 'Gourmet Frío', '2028-02-28', 0.10, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Bloc de Foie Gras con Trufa Negra', 35.00, 'Emulsión fina y homogénea de hígado graso de pato, enriquecida con generosos trozos de trufa de invierno (3%). Ideal para untar en tostas calientes.', true, 'Gourmet Frío', '2029-06-30', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Sobrasada de Cerdo Negro Mallorquín', 26.50, 'Auténtica sobrasada artesanal de raza porcina autóctona de Mallorca, curada en tripa natural. Un manjar ibérico para untar de textura fundente y sedosa.', false, 'Charcutería Selecta', '2026-10-15', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Coppa Italiana Curada', 28.00, 'Cabecero de lomo de cerdo al estilo italiano tradicional, marinado en vino tinto, frotado con especias y curado al aire, de vetado espectacular.', true, 'Charcutería Selecta', '2026-09-30', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');

-- Categoría: Dulces, Mermeladas y Mieles (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Mermelada Extra de Higo y Nuez', 8.50, 'Elaborada artesanalmente con higos negros de temporada y nueces tostadas troceadas, un acompañamiento indispensable para cualquier tabla de quesos fuertes.', true, 'Dulces', '2028-05-10', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Mermelada de Naranja Amarga Sevilla', 7.90, 'Auténtica receta británica elaborada con naranjas amargas recogidas en los patios sevillanos, la proporción perfecta de dulzor cítrico y cáscara.', true, 'Dulces', '2028-08-20', 0.15, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Crema de Gianduja Artesana', 15.50, 'Exquisita crema de avellanas del Piamonte (45%) trituradas a la piedra con chocolate con leche puro, sin aceites de palma añadidos ni grasas artificiales.', true, 'Dulces', '2027-11-30', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Miel Cruda de Romero', 12.00, 'Miel pura y sin pasteurizar extraída en frío de los montes mediterráneos. Color muy claro, aroma balsámico y propiedades beneficiosas para la garganta.', true, 'Dulces', '2030-12-31', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Miel de Acacia con Trufa Blanca', 18.50, 'Miel italiana muy suave de Acacia, en la cual macera finas láminas de trufa blanca de Alba. El contraste dulce-terroso es mágico sobre quesos azules.', true, 'Dulces', '2029-12-31', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Marron Glacé Selección Especial', 28.00, 'Castañas confitadas enteras de gran calibre sumergidas pacientemente en un almíbar ligero y vainillado, el pináculo de la repostería artesana otoñal.', true, 'Dulces', '2027-01-30', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Turrón de Jijona Artesano I.G.P.', 16.50, 'Turrón blando maestro elaborado en molino de piedra tradicional, usando miel de romero y más de un 70% de almendra marcona cruda finamente molida.', true, 'Dulces', '2027-04-15', 0.10, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Caja de Bombones Belgas Praliné', 35.00, 'Surtido premium de 24 bombones elaborados a mano por maestros chocolateros belgas. Rellenos de ganache, praliné de avellanas, caramelo y mazapán.', true, 'Dulces', '2026-10-30', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Tableta Chocolate Cacao 100% Criollo', 9.50, 'Tableta rústica de cacao criollo extremo de origen único sin azúcares añadidos, su intensa acidez frutal y largo postgusto desafían el paladar.', true, 'Dulces', '2028-02-15', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Crema de Pistacho de Bronte D.O.P.', 22.00, 'Intensa pasta dulce para untar elaborada exclusivamente con pistachos verdes procedentes del suelo volcánico siciliano de Bronte, una rareza gourmet.', false, 'Dulces', '2027-06-20', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');

-- Categoría: Vinos y Licores (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Vino Tinto Rioja Gran Reserva', 45.00, 'Un tinto elegante de la D.O.Ca. Rioja madurado 36 meses en roble americano y afinado en botella, desvela sedosas notas a vainilla, cuero y fruta compotada.', true, 'Vinos y Licores', '2040-12-31', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Vino Tinto Ribera del Duero Crianza', 26.50, 'Elaborado con Tempranillo 100%, con 12 meses en barrica nueva de roble francés. Destaca su estructura, tanino potente y aromas de fruta negra.', true, 'Vinos y Licores', '2035-12-31', 0.20, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Vino Blanco Albariño Rías Baixas', 19.80, 'Blanco atlántico joven, brillante y salino, con penetrante aroma floral a jazmín y frutas de hueso. La pareja innegable para todo tipo de marisco.', true, 'Vinos y Licores', '2030-12-31', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Vino Blanco Borgoña Chablis Premier Cru', 55.00, 'Vino blanco de la uva Chardonnay fermentado en acero, caracterizado por su pureza mineral, frescura ácida de piedra de tiza y sutil final cítrico.', true, 'Vinos y Licores', '2034-12-31', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Champagne Millésime Brut', 75.00, 'Champagne francés de añada, elaborado a partir de viñedos Grand Cru. Presenta burbuja diminuta y elegantes toques aromáticos a brioche y bollería tostada.', true, 'Vinos y Licores', '2040-12-31', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Cava Gran Reserva Brut Nature', 24.00, 'Cava sin azúcares añadidos tras su degüelle, reposado más de 30 meses en rima. Extraordinariamente seco, crujiente, estructurado y de gran integración carbónica.', true, 'Vinos y Licores', '2032-12-31', 0.15, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Vermut Rojo Artesano de Barrica', 16.50, 'Maceración de 40 botánicos diferentes sobre un vino blanco de calidad, envejecido en botas centenarias para conseguir amargor y toques amaderados especiados.', true, 'Vinos y Licores', '2038-12-31', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Ginebra Premium Botánica London Dry', 38.00, 'Destilada lentamente en alambiques de cobre usando enebro silvestre, cardamomo, cilantro y cítricos frescos mediterráneos. Muy limpia y refrescante.', true, 'Vinos y Licores', '2050-12-31', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Ron Agrícola Añejo Solera 15 Años', 65.00, 'Elaborado con jugo de caña puro en lugar de melazas, madurado en barricas ex-bourbon. Muy denso y complejo, rebosante de notas de toffee y cacao.', true, 'Vinos y Licores', '2050-12-31', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Vino Dulce Pedro Ximénez V.O.R.S.', 85.00, 'Auténtica reliquia de Jerez con más de 30 años de crianza certificada. El mosto densificado de pasas soleadas crea un elixir oscuro que sabe a higos.', true, 'Vinos y Licores', '2050-12-31', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');

-- Categoría: Salsas y Especias (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Flor de Sal de d''Es Trenc', 12.50, 'Los primeros cristales puros que flotan al amanecer en las salinas de Mallorca, cosechados artesanalmente. Se funden en boca ensalzando carnes a la brasa.', true, 'Especias', '2035-12-31', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Sal Rosa del Himalaya Gruesa', 8.90, 'Extraída de antiguas minas de sal en Pakistán, no está tratada ni refinada y es rica en hierro y minerales esenciales, ideal para el uso en molinillo.', true, 'Especias', '2035-12-31', 0.10, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Azafrán de La Mancha D.O.P.', 22.00, 'Tarro de cristal con hebras puras de azafrán manchego, secado a fuego lento de leña. Una pizca de este "oro rojo" aporta profundo sabor y color a tus arroces.', true, 'Especias', '2028-11-30', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Pimienta Negra de Kampot I.G.P.', 15.50, 'Considerada por chefs y críticos como la mejor pimienta negra del mundo, con unas sorprendentes notas herbales y de mentol fresco que perduran tras la molienda.', true, 'Especias', '2029-05-15', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Mostaza a la Antigua de Dijon', 7.50, 'Receta original en tarro de gres, contiene las semillas de mostaza enteras mezcladas con vino blanco, otorgando un carácter picante, rústico y crujiente.', true, 'Salsas', '2028-04-20', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Pesto Genovese Fresco D.O.P.', 11.20, 'Preparado artesanalmente solo con albahaca genovesa de hoja pequeña, piñones europeos, ajo dulce y Parmigiano, un viaje rápido al frescor de Italia.', false, 'Salsas', '2026-07-15', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Salsa Tartufata (Crema de Trufa)', 16.00, 'Exquisita crema densa elaborada a partir de champiñones picados, aceite de oliva virgen extra, especias y un 5% de auténtica trufa negra de verano.', true, 'Salsas', '2028-08-10', 0.20, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Pasta de Curry Rojo Tailandés', 6.80, 'Pasta concentrada de especias asiáticas y chiles frescos machacados a mortero, la base fundamental para elaborar currys tailandeses muy aromáticos y picantes.', true, 'Salsas', '2028-10-30', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Salsa de Soja Shoyu Artesanal', 14.50, 'Salsa fermentada lentamente en barriles de cedro durante más de un año en Japón. De sabor extremadamente complejo y umami profundo sin ser salada en exceso.', true, 'Salsas', '2029-01-15', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Pimentón de la Vera Dulce D.O.P.', 5.90, 'Latita metálica de pimentón secado y ahumado al humo de roble y encina en la región de Cáceres, confiriendo a los embutidos y guisos un sabor inigualable.', true, 'Especias', '2029-03-10', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');

-- Categoría: Pastas y Arroces Gourmet (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Arroz Bomba D.O. Valencia', 7.50, 'El arroz clásico para grandes paellas, su grano redondo no se rompe y tiene una altísima capacidad de absorber todos los matices y el sabor de los caldos.', true, 'Pastas y Arroces', '2028-06-30', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Arroz Carnaroli Especial Risotto', 8.20, 'Cosechado en la zona del Piamonte italiano, contiene mucho almidón, que se libera lentamente permitiendo la textura melosa perfecta en todo risotto.', true, 'Pastas y Arroces', '2028-09-15', 0.15, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Pasta Pappardelle al Huevo Artesana', 9.50, 'Largas cintas de pasta gruesa trefiladas en bronce para lograr rugosidad. El huevo campero aporta un color amarillo intenso y gran riqueza de sabor.', true, 'Pastas y Arroces', '2027-10-20', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Spaghetti al Nero di Seppia', 8.90, 'Finos espaguetis oscurecidos naturalmente amasados con tinta de sepia, los cuales otorgan un evocador sabor a mar y resultan visualmente sorprendentes en el plato.', true, 'Pastas y Arroces', '2027-11-15', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Raviolis Secos Rellenos de Trufa', 12.00, 'Pasta corta muy fina rellena y secada, que al hidratarse recupera un delicioso corazón trufado que inunda de aromas la cocina entera al hervirse.', false, 'Pastas y Arroces', '2027-05-10', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Macarrones Gigantes Paccheri', 7.90, 'Pasta napolitana artesanal con forma de enormes tubos de sémola de trigo duro. Quedan muy firmes y resisten ragús de carnes espesas e intensas.', true, 'Pastas y Arroces', '2028-01-30', 0.10, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Lentejas Caviar Beluga Orgánicas', 6.50, 'Llamadas así por su parecido estético al caviar, son pequeñas, de piel oscura y textura entera tras cocerlas, sin apenas deshacerse en ensaladas frías.', true, 'Legumbres Selectas', '2028-11-15', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Garbanzo Blanco Lechoso Andaluz', 7.20, 'Un garbanzo extra grueso y muy mantecoso al paladar que no suelta la piel. Un lujo imprescindible para preparar cocidos a fuego lento y potajes de bacalao.', true, 'Legumbres Selectas', '2028-10-10', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Alubia Tolosana (Pinta de Tolosa)', 8.50, 'Grano purpúreo casi negro, una vez cocida lentamente se vuelve mantequilla pura desatando un caldo tan espeso y sedoso que sorprende gratamente.', true, 'Legumbres Selectas', '2028-10-10', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Quinoa Real Boliviana Orgánica', 6.90, 'Seudocereal milenario andino de gran tamaño cultivado a alta altitud, libre de impurezas y muy rico en proteínas vegetales de asimilación completa.', true, 'Pastas y Arroces', '2028-04-20', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');

-- Categoría: Cafés, Tés e Infusiones (2 descuentos)
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Café Jamaica Blue Mountain', 55.00, 'Considerado uno de los mejores cafés del mundo y cultivado a más de 2000 metros, tiene acidez suave, nada de amargor y cuerpo floral elegante.', true, 'Cafés y Tés', '2027-12-31', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Café Colombia Geisha Especialidad', 32.00, 'Granos de la cotizada variedad botánica Geisha, de proceso lavado. Perfil de cata asombrosamente afrutado con potentes notas a melocotón y jazmín.', true, 'Cafés y Tés', '2027-10-15', 0.20, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Café Etiopía Yirgacheffe Grano', 18.50, 'Café arábica de origen africano procesado al natural, desprende olores a bergamota y té negro, ideal para disfrutar en preparaciones de filtro manual.', true, 'Cafés y Tés', '2027-08-30', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Té Matcha Ceremonial Grado A', 45.00, 'Polvo de té verde molido a la piedra proveniente de los mejores cultivos de sombra de Uji en Japón. Su amargor es nulo y su color es verde esmeralda brillante.', true, 'Cafés y Tés', '2027-06-15', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Té Negro Earl Grey Premium', 14.50, 'Hojas completas de té negro de altura de la región de Assam delicadamente perfumadas con aceite esencial puro extraído de bergamotas de la región de Calabria.', true, 'Cafés y Tés', '2028-05-10', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Té Verde Sencha Japonés (Hojas)', 16.00, 'Té verde no fermentado y cocido al vapor siguiendo el método de Japón tradicional, libera un sabor refrescante, profundamente vegetal y muy iodado.', true, 'Cafés y Tés', '2028-01-20', 0.15, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Té Blanco Agujas de Plata (Silver Needle)', 28.00, 'Té muy raro cosechado a mano usando únicamente los primeros y tiernos brotes blancos vellosos antes de que la hoja se abra al sol de primavera chino.', false, 'Cafés y Tés', '2027-11-30', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Infusión Frutos del Bosque Salvajes', 11.00, 'Mezcla de hibisco, rosa mosqueta, bayas de saúco y arándanos, infusión sin nada de teína, muy saludable y afrutada, deliciosa tanto en frío como en caliente.', true, 'Cafés y Tés', '2028-09-15', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Café Descafeinado Swiss Water', 19.00, 'Granos de arábica orgánicos libres de cafeína al 99.9% gracias al costoso proceso ecológico con agua natural que conserva perfectamente su rico perfil aromático.', true, 'Cafés y Tés', '2027-10-10', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');
INSERT INTO producto (nombre, precio, descripcion, stock, categoria, fecha_caducidad, descuento, imagen_url) VALUES ('Infusión Manzanilla, Miel y Vainilla', 9.50, 'Flores grandes y enteras de camomila dulce recolectada en cultivos biodinámicos, combinadas con notas reales de vainilla bourbon y toques dulces de miel de flores.', true, 'Cafés y Tés', '2029-02-28', 0.0, 'https://static.thenounproject.com/png/1077596-200.png');



/*
INSERT INTO usuario (dtype, codigo_usuario, username, password, roles, nombre) VALUES ('A', 1001, 'admin', '{noop}admin', 'ADMIN', 'Administrador');
INSERT INTO usuario (dtype, codigo_usuario, username, password, roles, nombre) VALUES ('C', 1002, 'user', '{noop}user', 'CLIENTE', 'Usuario Normal');
*/
